### ISSUE TITLE
2.1.18 - BOS Mats Not Displaying Correct Entries

### ISSUE THREAD

**Issue by waztros** [geoffhumphrey/brewcompetitiononlineentry#1149] opened 2020-03-11 19:14 UTC
Version: 2.1.18

Installation URL: https://hvhb.brewcomp.com

Is your installation hosted on brewcompetition.com or brewcomp.com? Yes! Paid subscription for brewcomp.com

Description of Issue: BOS Mat is not displaying the correct entries on it!!!

Admin>Competition Preparation>Style Types>Manage:
All the types (Beer, Mead and Cider) are set to 1st, 2nd and 3rd places.

Admin>Preferences>Competition Organization>Maximum Places in BOS:
This is set to only "1". I only want 1st place from each "Table" to advance to the Beer BOS table for judging. Mead and Cider are a different story where we have a seperate BOS and push the top 3 meads and the top 3 ciders to a BOS table but that is not the issue at the moment.

The problem is happening here:
Admin>Reports>BOS Cup Mats>Beer - Judging Numbers:
I am getting a mix of 1st, 2nd and 3rd place beer entries on the place mats. We currently only have 1/2 of the scoring entered into the website so far but I would only expect to only see 1st place entries on the current BOS Mat.

Please Help!!! Need this working properly before 3/14/2020

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by ercousin** [comment] 2020-03-11 19:23
This appears to be a duplicate of:

#1071

**Comment by waztros** [comment] 2020-03-11 19:31
> 
> 
> This appears to be a duplicate of:
> 
> #1071

@ercousin: Thanks for the work around! ~Eric

**Comment by geoffhumphrey** [comment] 2020-03-11 19:41
Beat me to it, Eric. Also, #1117 is related. On the list to address in the planned conversion late this year.

**Closed** 2021-02-10 14:54 UTC
Labels: duplicate, enhancement, in latest master commit, v2.2.0
