### ISSUE TITLE
Version 2.5.0: Submitting Digital Scoresheets for Cider and Mead results in page not found due to missing Mouthfeel data

### ISSUE THREAD

**Issue by jiblits** [geoffhumphrey/brewcompetitiononlineentry#1428] opened 2023-06-24 17:38 UTC
**Verify the Following**
Reporting About the Latest Version? Yes

Searched Issue Reports for Bug? Yes

Reviewed the Good To Know Issue Reports? Yes

**BCOE&M Info**
Version: 2.5.0
Installation URL:  http://blazingpaddles.truegrist.ca
Hosted Installation? No

**Describe the Bug**
Submitting an digital Cider or Mead scoresheet results in a 404 and the form data being lost.

**To Reproduce**
- With a Cider or Mead entry
- Create a judging table and assign subscribed judges to the table
- Open the Mead or Cider entry and complete the online scoresheet
- Submit the form

**Expected Results**
The user is returned to the judging dashboard

**Actual Results**
The user is presented with a blank page with a of **Page Not Found**. When the returning to the index of the judging site the following error information is presented in a banner at the top of the page.

**Screenshots**
<img width="704" alt="Screenshot 2023-06-24 at 11 58 57" src="https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/33376830/25fef8b7-7259-4673-9d0c-4ad1a54f43c5">

**Server Environment**
- PHP Version:
- MySQL Version: 
- Other Info: [if applicable. Apache, nginx, etc.]

**Local Environment**
 - OS: Mac OS 13.4.1
 - Browser: Google Chrome
 - Browser Version: 114.0.5735.133

**Additional Context**
I am not the administrator of the judging site but I can get you the additional server details if those would help.

**Comment by geoffhumphrey** [comment] 2023-06-26 17:24
Hi @jiblits, thanks for reporting. Question - which scoresheet are you using? For Ciders and/or Meads, there are two available - "Traditional" or "Structured." Knowing that will help me try to diagnose the cause.

**Comment by jiblits** [comment] 2023-06-27 00:38
Hello @geoffhumphrey we were using the scoresheets that had the sliders on them. I believe that’s the structured one. I wasn’t the administrator of the competition so I’m not 100% certain.

**Comment by slevander** [comment] 2023-08-01 17:01
Last weekend we had the same issue using Classic scoresheets in 2.5.0.

**Comment by geoffhumphrey** [comment] 2023-08-01 17:46
This has been addressed in v2.6.0. Apologies for not including this issue in the [2.6.0 Milestone](https://github.com/geoffhumphrey/brewcompetitiononlineentry/milestone/30).

**Closed** 2023-08-09 22:11 UTC
Labels: bug, in latest master commit, confirmed, v2.6.0
