### ISSUE TITLE
[2.3.1] PayPal Checkout not populating Total Fees

### ISSUE THREAD

**Issue by jimpdx** [geoffhumphrey/brewcompetitiononlineentry#1245] opened 2021-10-21 06:16 UTC
Version: 2.3.1
Self Hosted Installation URL: https://fallclassic.oregonbrewcrew.org

Description of Issue:
I noticed today (when paying for my own entries in 2.3.1 that clicking "Pay with PayPal" was not pre-populating the "Total Fees" variable that I think you are still sending in your code (ref: https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/master/sections/pay.sec.php#L178)

![image](https://user-images.githubusercontent.com/867051/138221570-5899ffd0-d87e-421e-bc78-5cb2dfe2a7bd.png)

We have been using PayPal in BCOEM without any issues for years. Unless I am crazy, this is the first time the payment form did not pre-populate the amount and asked me to enter it? Seems like it would allow participants to easily pay the wrong amount?

This could be a change on the PayPal side of things, as I know the code has not been updated in some time. I didn't see any other open issues relating to this so I thought I might bring it up? I am happy to research further if you have any PP resources/dev guides I can look over.

**Comment by geoffhumphrey** [comment] 2021-10-21 15:34
Confirmed, and thank you for reporting and providing the fix, @jimpdx. For those experiencing this issue, implement the fix described in pull [#1246](https://github.com/geoffhumphrey/brewcompetitiononlineentry/pull/1246) or download the latest master commit and upload/replace the /sections/pay.sec.php file to your server.

**Comment by grmelacz** [comment] 2021-11-22 16:46
I think this bug might be connected with one that just happened at our competition today. One of the contestants has 2 entries in the competition but the received payment was just for one. He confirmed he payed just for one, though the note in the PayPal transactions displays two: `238|107-108`. The problem is both entries were marked as payed though the total was not correct!

I don't wanna hijack this thread, so in case this is a separate problem, please move my comment to a new thread accordingly.
<img width="2221" alt="Screenshot 2021-11-22 at 17 43 06" src="https://user-images.githubusercontent.com/41264018/142901319-984fcc27-913e-4723-ac03-ed715ac8768a.png">
<img width="943" alt="Screenshot 2021-11-22 at 17 42 29" src="https://user-images.githubusercontent.com/41264018/142901328-36a3265a-1eda-46d4-ac0a-00fa0c9fe881.png">

**Comment by geoffhumphrey** [comment] 2021-11-23 15:47
Hello @grmelacz, this could be related if you're **not** adding the PayPal fees to the entrant's total. The fix described in pull #1246 provides a fix.

**Comment by grmelacz** [comment] 2021-11-24 07:16
Yes, I do not have adding fees enabled. Makes sense. I've already applied the mentioned fix, will let you know if the bug occurs again. Thanks!

**Closed** 2021-11-24 23:08 UTC
Labels: bug, in latest master commit, confirmed, v2.3.2
