### ISSUE TITLE
New install of BCOE - Not working

### ISSUE THREAD

**Issue by webdevsoup** [geoffhumphrey/brewcompetitiononlineentry#800] opened 2017-08-05 03:57 UTC
Ok, so I forked the repo, and then downloaded locally.  I followed the setup, and adjusted my config.php file.  However, when I run the web setup, I end up getting an error that states "Invalid default value for 'scoreType'".  

If I run it directly on SSH, it appears to install all tables, but when I go to step 2, it tells me "DATABASENAME.system" doesn't exist.  

I'm not sure what's going on with this, it should be pretty straight forward.

PHP version: 5.6.30
Server version: 5.6.36 - MySQL Community Server (GPL)

**Comment by geoffhumphrey** [comment] 2017-08-08 05:14
Confirmed. There was a missing comma in an SQL command that was mucking things up. Fixed in latest commit.

**Comment by ercousin** [comment] 2017-08-10 16:09
Hi Geoff,

You mentioned a missing comma, but your commit touches 37 files. Could you tell us which file had the missing comma?

Looking at the git history, it seems there there are a lot of bug fixes after the broken 2.1.10 release, will there be a re-release of 2.1.10, or a quick 2.1.11 follow up?

Thanks,
Eric

**Comment by geoffhumphrey** [comment] 2017-08-11 18:56
Sure thing. The missing comma was in the /setup/install_db.setup.php file ([diff](https://github.com/geoffhumphrey/brewcompetitiononlineentry/commit/a819da30e4afc17e3c32ba8ed77d6a3a0595eb49#diff-99456562bdab3ab0c3df487bc9da8330L741)).

There will be a release of a "full" version of 2.1.10, currently targeted for August 15. The current release is a beta pre-release and some bugs have been discovered since its release on July 25.

**Closed** 2017-10-20 04:56 UTC
Labels: bug, confirmed, in latest master commit, v2.1.10
