### ISSUE TITLE
URGENT: Issue assigning judges to tables

### ISSUE THREAD

**Issue by michaeltrego** [geoffhumphrey/brewcompetitiononlineentry#838] opened 2017-10-20 13:57 UTC
When attempting to assign judges to tables, some of the tables are not showing the radio button selections to assign the judge.  Please advise ASAP - our competition is tomorrow!

![image](https://user-images.githubusercontent.com/22302281/31824409-ec29f556-b57c-11e7-8e09-d0418e86d975.png)

**Comment by geoffhumphrey** [comment] 2017-10-20 14:49
Make sure that all tables have been assigned to rounds. For the affected tables without radio buttons to assign judges, go to the assign tables to rounds screen and change the round to something other than what's listed. Then, change it back to the intended round. This has worked for me in the past as a temporary solution. I'll be investigating the cause.

**Comment by michaeltrego** [comment] 2017-10-20 15:31
Thanks Geoff - that workaround seems to have done the trick - thanks for the quick response!

**Comment by geoffhumphrey** [comment] 2017-10-20 16:15
No problem. In looking at your DB, it appears that some entries in the judging_flights table had NULL for their assigned flight. Hence why you weren't able to assign any judges to tables where those entries resided.

For the next release, I enhanced the assign to round code to check whether all entries for a given table or flight in the judging_flights have a round assigned. If not, the Assign Tables/Flights to Rounds drop-down will indicate "Not assigned to a round."

**Closed** 2017-10-20 17:02 UTC
Labels: bug, confirmed, in latest master commit, v2.1.10
