### ISSUE TITLE
Unable to change site preferences, add admins, ets

### ISSUE THREAD

**Issue by tpklieb** [geoffhumphrey/brewcompetitiononlineentry#547] opened 2016-02-18 02:00 UTC
Trying to get the new version up and running for my comp. I need to add a few users to be admins, but the page to change the permissions is blank. Same deal for trying to upload a logo, change accepted style categories,

**Comment by geoffhumphrey** [comment] 2016-02-18 15:19
@tpklieb, I'm not able to duplicate the issues you have reported. Make sure that you have run the update script and please check your error logs on your server (they will be in the root folder and subfolders). If there are any logs, please post the text...

**Comment by tpklieb** [comment] 2016-02-18 15:22
Thanks for the reply back. Looks like we are on version 2.0.0 tight now,
which I read has a bug that may be giving me those problems. I've contacted
our web guru to have him update the version to 2.0.1 to see if that fixes
it.

**Comment by csaunders** [comment] 2016-05-10 00:42
I had the exact same issue when setting mine up. I have a feel the cause might be from a bug in one of the generated `$brewer` queries regarding page size. I couldn't see any users, noticed this "page limit" thing and added a default page limit by setting `Records Displayed` to `20` in the Preferences section (/index.php?section=admin&go=preferences).

I'd suggest attempting to replicate the issue by creating a fresh install, adding some users via the admin manually then going to view them (/index.php?section=admin&go=participants). The app knows there are users there (the participant status popup shows correct counts) but it's not rendering any rows.

**Closed** 2016-05-24 14:01 UTC
Labels: can't reproduce

**Comment by csaunders** [comment] 2016-05-24 14:49
Is there a commit or PR that resolved this issue?

- Chris Saunders / sndrs.ca

**Comment by geoffhumphrey** [comment] 2016-05-24 15:11
Unfortunately, I could not recreate this issue in any of my test environments, so I'm unable to track down the possible causes. I will keep review my server logs to see if there's some anomalies resulting from that script.

**Comment by csaunders** [comment] 2016-05-24 15:30
Even after full database tear downs?

- Chris Saunders / sndrs.ca

**Comment by geoffhumphrey** [comment] 2016-05-24 15:35
Yep. Sorry.
