### ISSUE TITLE
Entry Check in - only manual option

### ISSUE THREAD

**Issue by MarieAnnick** [geoffhumphrey/brewcompetitiononlineentry#1072] opened 2019-06-17 13:40 UTC
Version: 2.1.14

Installation URL: https://ehg.ca/abc

Is your installation hosted on brewcompetition.com or brewcomp.com?
no

Description of Issue:
Entry Check In - only Manual available. Barcode/QR Code (Bottle Labels Only) option selected in Website Preferences, Printed Entry Form and/or Bottle Labels, Print Multiple Entries at a Time

The Barcode Scanner and QR scanner options are no longer available. Even under the previous version, choosing Manual Entry Check In brought you to a page where you could input multiple entries. Now, it brings you to the Administration: Entries page. Staff must search the entry, then check it as received and update the page one entry at a time. As you can see, this is extraordinarily time consuming as everything depends on the internet connection/server/computer. 

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment] 2019-06-18 17:09
Hi @MarieAnnick - There should be three Entry Check-In options under the _Entry Sorting_ heading on the Admin dashboard:
![2019-06-17_9-19-06](https://user-images.githubusercontent.com/5216502/59704482-7639fd80-91b9-11e9-9a57-05c1c23d77cf.png)

Are you not seeing either of these?

**Comment by MarieAnnick** [comment] 2019-06-18 17:27
That's the issue. It's not there. Clip attached.

[image: image.png]

**Comment by geoffhumphrey** [comment] 2019-06-18 17:41
Ah, I see. Those will only show if you have chosen a bottle label option that has a barcode/QR code,

Check Admin > Preferences > Website under the "Entries" heading to verify.

![2019-06-18_11-39-32](https://user-images.githubusercontent.com/5216502/59706547-e8144600-91bd-11e9-84e9-a5708eff7db7.png)

**Comment by geoffhumphrey** [comment] 2019-06-18 17:48
Whoops. Image cursor in the wrong place... but you get the idea. Choose one that has "with Barcode/QR Code."

**Comment by MarieAnnick** [comment] 2019-06-18 18:02
I have print multiple entries at a time, barcode/qr code selected.

**Comment by geoffhumphrey** [comment] 2019-06-18 18:21
My apologies - I wasn't clear. I should have mentioned that this was a confirmed bug in 2.1.14 that has since been fixed in the latest version (2.1.17). 

I'm assuming that you're at the sorting stage and, therefore, aren't needing entrants to bring bottle labels. If that's the case, go ahead and choose one of the "Print Single" options. Then those options will show on the Dashboard. Or, update to 2.1.17.

**Comment by MarieAnnick** [comment] 2019-06-18 18:23
Ohhhhh, okay. Thanks for letting me know, we'll be upgrading right after
the competition then. Thanks.

**Closed** 2019-07-04 12:41 UTC
